### ISSUE TITLE
I also made a Datomic buildpack

### ISSUE THREAD

**Issue by raymcdermott** [kikofernandez/heroku-buildpack-datomic-clojure#7]
Based on the Java buildpack of Heroku

https://github.com/opengrail/heroku-buildpack-datomic

I don't know if you are still active but I would be happy to collaborate and either donate code or take PRs.

Cheers

Ray

**Comment by kikofernandez** [comment]
hi, I am quite busy at the moment with other projects. If I have time, I'll issue a PR to your buildpack. Thanks for letting me know!

**Comment by raymcdermott** [comment]
OK, thanks, that would be nice.
On 20 December 2015 at 13:55:37, Kiko (notifications@github.com) wrote:

hi, I am quite busy at the moment with other projects. If I have time, I'll issue a PR to your buildpack. Thanks for letting me know!
